package com.StreamlineLearn.UserManagement.enums;

public enum Field {
    BUSINESS,
    COMPUTER_SCIENCE,
    ENGINEERING,
    MATHEMATICS_AND_STATISTICS,
    PHYSICAL_SCIENCES,
    BIOLOGICAL_SCIENCES,
    HEALTH_PROFESSIONS,
    LEGAL_PROFESSIONS,
    EDUCATION,
    SOCIAL_SCIENCES,
    ARTS_AND_HUMANITIES,


}
