package com.StreamlineLearn.UserManagement.model;

public enum Expertise {
    SOFTWARE_ENGINEERING,
    DATABASE_MANAGEMENT,
    NETWORKING,
    MACHINE_LEARNING,
    ARTIFICIAL_INTELLIGENCE,
    WEB_DEVELOPMENT,
    CYBER_SECURITY,
    PHYSICS,
    MATHEMATICS,
    BIOLOGY,
    CHEMISTRY,
    BUSINESS_STRATEGY,
    MARKETING,
    FINANCE,
    MANAGEMENT,
    EDUCATION_TECHNOLOGY,
    CURRICULUM_DESIGN,
    OTHER;
}
