export const Department = {
    COMPUTER_SCIENCE: 'COMPUTER_SCIENCE',
    ENGINEERING: 'ENGINEERING',
    MATHEMATICS: 'MATHEMATICS',
    PHYSICS: 'PHYSICS',
    BIOLOGY: 'BIOLOGY',
    CHEMISTRY: 'CHEMISTRY',
    BUSINESS: 'BUSINESS',
    EDUCATION: 'EDUCATION',
    SOCIAL_SCIENCES: 'SOCIAL_SCIENCES',
    ARTS: 'ARTS',
    OTHER: 'OTHER'
};
