export const Education = {
    HIGH_SCHOOL_DIPLOMA: 'HIGH_SCHOOL_DIPLOMA',
    ASSOCIATE_DEGREE: 'ASSOCIATE_DEGREE',
    BACHELOR_DEGREE: 'BACHELOR_DEGREE',
    MASTER_DEGREE: 'MASTER_DEGREE',
    PROFESSIONAL_SCHOOL_DEGREE: 'PROFESSIONAL_SCHOOL_DEGREE',
    DOCTORATE_DEGREE: 'DOCTORATE_DEGREE'
};
