export const Expertise = {
    SOFTWARE_ENGINEERING: 'Software Engineering',
    DATABASE_MANAGEMENT: 'Database Management',
    NETWORKING: 'Networking',
    MACHINE_LEARNING: 'Machine Learning',
    ARTIFICIAL_INTELLIGENCE: 'Artificial Intelligence',
    WEB_DEVELOPMENT: 'Web Development',
    CYBER_SECURITY: 'Cyber Security',
    PHYSICS: 'Physics',
    MATHEMATICS: 'Mathematics',
    BIOLOGY: 'Biology',
    CHEMISTRY: 'Chemistry',
    BUSINESS_STRATEGY: 'Business Strategy',
    MARKETING: 'Marketing',
    FINANCE: 'Finance',
    MANAGEMENT: 'Management',
    EDUCATION_TECHNOLOGY: 'Education Technology',
    CURRICULUM_DESIGN: 'Curriculum Design',
    OTHER: 'Other'
};
