export const Field = {
    BUSINESS: 'BUSINESS',
    COMPUTER_SCIENCE: 'COMPUTER_SCIENCE',
    ENGINEERING: 'ENGINEERING',
    MATHEMATICS_AND_STATISTICS: 'MATHEMATICS_AND_STATISTICS',
    PHYSICAL_SCIENCES: 'PHYSICAL_SCIENCES',
    BIOLOGICAL_SCIENCES: 'BIOLOGICAL_SCIENCES',
    HEALTH_PROFESSIONS: 'HEALTH_PROFESSIONS',
    LEGAL_PROFESSIONS: 'LEGAL_PROFESSIONS',
    EDUCATION: 'EDUCATION',
    SOCIAL_SCIENCES: 'SOCIAL_SCIENCES',
    ARTS_AND_HUMANITIES: 'ARTS_AND_HUMANITIES'
};
