# Spring application configurations
spring:
  application:
    # Name of the application
    name: Assessment-Management

  # Database source configurations
  datasource:
    # Database URL
    url: jdbc:mysql://localhost:3306/assessment_database
    # Database username
    username: root
    # Database password
    password: Pqr#^(XYZ&*(!
    # Driver class name
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA configurations
  jpa:
    # Hibernate configurations
    hibernate:
      # DDL auto setting
      ddl-auto: create-drop
    # Show SQL queries
    show-sql: true
    # Hibernate properties
    properties:
      hibernate:
        # Format SQL queries
        format_sql: true
        # Database type
        database: mysql
        # Database dialect
        dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: assessment
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    topic:
      name: user_topic

# Server configurations
server:
  port: 8484

# Management configurations
management:
  tracing:
    sampling:
      probability: 1.0

# Logging configurations
logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE
